### ISSUE TITLE
using windows and anaconda

### ISSUE THREAD

**Issue by Miltonrosenbach** [JostineHo/real-time_emotion_analyzer#2]
I am trying to run your script on windows. When I use opencv 3 (with python 3.5) I have the following error:

```
Problem occurred during compilation with the command line below:
"C:\Users\stimulus\Anaconda3\envs\opencv3\Library\mingw-w64\bin\g++.exe" -shared -g -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=4096 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\numpy\core\include" -I"C:\Users\stimulus\Anaconda3\envs\opencv3\include" -I"C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\gof" -L"C:\Users\stimulus\Anaconda3\envs\opencv3\libs" -L"C:\Users\stimulus\Anaconda3\envs\opencv3" -o C:\Users\stimulus\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.5.3-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\stimulus\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.5.3-64\lazylinker_ext\mod.cpp -lpython35
Traceback (most recent call last):

  File "<ipython-input-1-f3c221dee664>", line 1, in <module>
    runfile('C:/Users/stimulus/Desktop/Face reconition/real-time_emotion_analyzer-master/real-time.py', args='haarcascade_frontalface_default.xml', wdir='C:/Users/stimulus/Desktop/Face reconition/real-time_emotion_analyzer-master')

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 879, in runfile
    execfile(filename, namespace)

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/stimulus/Desktop/Face reconition/real-time_emotion_analyzer-master/real-time.py", line 6, in <module>
    from keras.models import model_from_json

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>
    from .. import backend as K

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\keras\backend\__init__.py", line 80, in <module>
    from .theano_backend import *

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\keras\backend\theano_backend.py", line 3, in <module>
    import theano

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)

  File "C:\Users\stimulus\Anaconda3\envs\opencv3\lib\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

. collect2.exe: error: ld returned 1 exit statusdir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.5.3-64/lazylinker_ext/mod.cpp:976: undefined reference to `__imp__Py_TrueStruct'Error'e undefined references to `__imp__Py_NoneStruct' followow
```

I also tried to use openvc2 (with python 2.7) but was unable to install tensorflow.

What are the prerequisities to run the script on windows?

**Comment by lawup** [comment]
Change the real-time.py
Line 43
flags=cv2.cv.CV_HAAR_SCALE_IMAGE  #opencv2
to
flags=cv2.CASCADE_SCALE_IMAGE      #opencv3
