### ISSUE TITLE
something error,,,,,,

### ISSUE THREAD

**Issue by n454149301** [JostineHo/real-time_emotion_analyzer#3]
$     python real-time.py haarcascade_frontalface_default.xml 

Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(trainable=True, filters=32, use_bias=True, bias_regularizer=None, input_dtype="float32", batch_input_shape=[None, 1, ..., activation="relu", kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, padding="same", strides=[1, 1], name="convolution2d_10", bias_constraint=None, data_format="channels_first", kernel_regularizer=None, kernel_size=(3, 3))`
2018-01-23 17:36:54.464844: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=32, use_bias=True, name="convolution2d_11", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=32, use_bias=True, name="convolution2d_12", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(name="maxpooling2d_4", trainable=True, data_format="channels_first", pool_size=[2, 2], padding="valid", strides=[2, 2])`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=64, use_bias=True, name="convolution2d_13", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=64, use_bias=True, name="convolution2d_14", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=64, use_bias=True, name="convolution2d_15", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(name="maxpooling2d_5", trainable=True, data_format="channels_first", pool_size=[2, 2], padding="valid", strides=[2, 2])`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=128, use_bias=True, name="convolution2d_16", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=128, use_bias=True, name="convolution2d_17", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(kernel_initializer="glorot_uniform", kernel_constraint=None, activity_regularizer=None, trainable=True, padding="same", strides=[1, 1], filters=128, use_bias=True, name="convolution2d_18", bias_regularizer=None, bias_constraint=None, data_format="channels_first", kernel_regularizer=None, activation="relu", kernel_size=(3, 3))`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(name="maxpooling2d_6", trainable=True, data_format="channels_first", pool_size=[2, 2], padding="valid", strides=[2, 2])`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_4", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=256, kernel_initializer="glorot_uniform", use_bias=True, activation="relu")`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3, trainable=True, name="dropout_3")`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_5", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=256, kernel_initializer="glorot_uniform", use_bias=True, activation="relu")`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.3, trainable=True, name="dropout_4")`
/usr/local/lib/python2.7/dist-packages/Keras-2.1.3-py2.7.egg/keras/engine/topology.py:1269: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(name="dense_6", bias_regularizer=None, bias_constraint=None, activity_regularizer=None, trainable=True, kernel_constraint=None, kernel_regularizer=None, input_dim=None, units=6, kernel_initializer="glorot_uniform", use_bias=True, activation="softmax")`
Traceback (most recent call last):
  File "real-time.py", line 21, in <module>
    model.load_weights('model.h5')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 723, in load_weights
ImportError: `load_weights` requires h5py.

why...................................................................................

**Comment by n454149301** [comment]
pip install h5py

my false.
