### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by shixingya** [JostineHo/real-time_emotion_analyzer#7]
python real-time.py haarcascade_frontalface_default.xml
2021-09-07 21:38:57.577335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-09-07 21:38:57.584970: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-09-07 21:39:02.498623: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-09-07 21:39:02.507183: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-09-07 21:39:02.515771: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-09-07 21:39:02.525751: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-09-07 21:39:02.533076: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-09-07 21:39:02.542562: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
2021-09-07 21:39:02.550462: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-09-07 21:39:02.562027: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-09-07 21:39:02.569341: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-09-07 21:39:02.593552: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\Users\shixingya\code\real-time_emotion_analyzer-master\real-time.py", line 18, in <module>
    model = model_from_json(loaded_model_json)
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\model_config.py", line 104, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\sequential.py", line 432, in from_config
    layer = layer_module.deserialize(layer_config,
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\generic_utils.py", line 681, in deserialize_keras_object
    deserialized_obj = cls.from_config(cls_config)
  File "C:\Users\shixingya\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 748, in from_config
    return cls(**config)
TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'

**Comment by Luanjd** [comment]
I have the same error, did you solve it?
